_commit: v1.6.12-10-g27c763c
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: true
helmCrds: false
helmName: promtail
helmRelease: promtail
helmRepo: https://grafana.github.io/helm-charts
helmValues: helm/values.yaml
helmVersion: ''
ingress: false
labels: ''
name: promtail
namespace: promtail
pvc: false
reloader: false
resources: []
service: false
serviceAccount: false
upstreamURL: https://grafana.com/docs/loki/latest/send-data/promtail/
url: https://github.com/charlesthomas/homelab-promtail
