_commit: v1.12.1-6-gbf0c0a5
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: daemon-sets.yaml
backups: false
helm: false 
homepageEnabled: false
ingress: false
labels: ''
name: promtail
namespace: promtail
pvc: false
reloader: false
resources:
  - configmaps.yaml
  - rbac.yaml
  - service-accounts.yaml
service: false
serviceAccount: false
upstreamURL: https://grafana.com/docs/loki/latest/send-data/promtail/
url: https://github.com/charlesthomas/homelab-promtail
