---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: promtail

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-promtail

resources:
- resources/configmaps.yaml
- resources/daemon-sets.yaml
- resources/namespaces.yaml
- resources/rbac.yaml
- resources/service-accounts.yaml
