---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: promtail

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-promtail

resources:
- resources/namespaces.yaml
helmCharts:
- name: promtail
  namespace: promtail
  releaseName: promtail
  repo: https://grafana.github.io/helm-charts
  valuesFile: helm/values.yaml
