---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: promtail

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-promtail

resources:
- resources/namespaces.yaml
patches:
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: promtail
      namespace: promtail
      annotations:
        gethomepage.dev/href: https://promtail.crt.house
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: 
        gethomepage.dev/group: 
        gethomepage.dev/icon: promtail
        gethomepage.dev/name: promtail
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
helmCharts:
- name: promtail
  namespace: promtail
  releaseName: promtail
  repo: https://grafana.github.io/helm-charts
  valuesFile: helm/values.yaml
