---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    repo: https://github.com/charlesthomas/homelab-promtail
  labels:
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/name: promtail
  name: promtail
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    repo: https://github.com/charlesthomas/homelab-promtail
  labels:
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/name: promtail
  name: promtail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promtail
subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: promtail
