---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    repo: https://github.com/charlesthomas/homelab-promtail
  labels:
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/name: promtail
  name: promtail
  namespace: promtail
